// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbzFOPmcifX4KC-QX1MVi9vSE3RkeN8Ye6NO4pr7u1KZ-Ai3qNqK3OrHRZxZ_4qPGmmS/exec";
